name: easy_eval_3d

gpu_ids: 0
num_threads: 1
batch_size: 1
infer: True

# data
random_multiview: False
cameras: [0, 1, 2, 3]
val_cameras: [0, 1, 2, 3]
persons: [0]
frames: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

test_dataroot: "T:/at3dcv_project/data/Synthetic/first_trial"
gt_paths: "T:/at3dcv_project/data/Synthetic/first_trial/Obj/person_0/Combined"
eval_wo_reconstruct: True
pred_paths: "F:/SS23/AT3DCV/at3dcv_project/outputs/reconstruction/07_16-18_36_50"
# human_paths:
# cloth_paths:
num_samples_for_eval: 5000
save_pcd_for_eval: True
save_pcd_dir: "F:/SS23/AT3DCV/at3dcv_project/outputs/reconstruction/07_16-18_36_50"

# network
coarse_part: True
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

# path
load_netG_checkpoint_path: checkpoints/synthetic_first_trial_overfitting_coarse/netG_epoch_33
load_netN_checkpoint_path: checkpoints/demo/netN_latest

# smpl
smpl_faces: lib/data/smplx_multi.obj

# marching cube
resolution: 512
mc_threshold: 0.5