# Overfits with ground truth data
name: first_trial_coarse

coarse_part: True
infer: False

# TRAINING PARAMETERS
gpu_ids: 0
num_threads: 6
batch_size: 1
serial_batches: False
pin_memory: False
learning_rate: 1e-3
num_epoch: 64

val_size: 5
val_type: "notmse"

# DATASET PATH
train_dataroot: data/Synthetic/easy
val_dataroot: data/Synthetic/easy
smpl_faces: lib/data/smplx_multi.obj
smpl_path: Obj
obj_path: Obj
loadSize: 512

# DATASET PARAMETERS
cameras: [0, 1, 2, 3]
random_multiview: False
persons: [0]
train_frames: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530]
val_frames: [5, 25, 45, 65, 85, 105, 125, 145, 165, 185, 205, 225, 245, 265, 285, 305, 325, 345, 365, 385, 405, 425, 445, 465, 485, 505, 525, 545]


# SAMPLING RELATED
sigma: 0.25 # Pertupation standard deviation for positions
num_sample_inout: 12000


# network
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

# PLOTTING PARAMETERS
freq_plot: 10 
freq_save: 50
freq_save_ply: 50
freq_val: 5 # Epochs

# PATHS
load_netN_checkpoint_path: checkpoints/demo/netN_latest

resolution: 512
mc_threshold: 0.5