name: multihuman_single_trial
log_path: logs/multihuman_single_trial
gpu_ids: 0
num_threads: 1
batch_size: 1
infer: True
infer_reverse: True

# data 
num_views: 10
yaw_list: [0, 36, 72, 108, 144, 180, 216, 252, 288, 324]
# [0, 90, 180, 270]
flip_x: False

# network
fine_part: True
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

# path
load_netG_checkpoint_path: checkpoints/demo/netG_latest
load_netN_checkpoint_path: checkpoints/demo/netN_latest

# smpl
smpl_faces: lib/data/smplx_multi.obj

# marching cube
resolution: 512
mc_threshold: 0.5