name: synthetic_first_trial_gt
log_path: logs/synthetic_first_trial_gt
gpu_ids: 0
num_threads: 4
batch_size: 1
infer: False

coarse_part: True

# data
num_views: 4
flip_x: False

# network
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

# smpl
smpl_faces: lib/data/smplx_multi.obj

load_netN_checkpoint_path: checkpoints/demo/netN_latest

serial_batches: True

# marching cube
resolution: 256
mc_threshold: 0.6

# debug_data: True