# Overfits with ground truth data
name: synthetic_overfitting_coarse

coarse_part: True
infer: False

# TRAINING PARAMETERS
gpu_ids: 0
num_threads: 4
batch_size: 1
serial_batches: True
pin_memory: False
learning_rate: 1e-3
num_epoch: 50

val_size: 5

# DATASET PATH
train_dataroot: T:/at3dcv_project/data/Synthetic/easy
val_dataroot: T:/at3dcv_project/data/Synthetic/easy
smpl_faces: lib/data/smplx_multi.obj
smpl_path: Obj
obj_path: Obj
loadSize: 512

# DATASET PARAMETERS
cameras: [0, 2, 6, 10]
random_multiview: False
persons: [0]
frames: [0, 1, 2, 3]

# SAMPLING REALTED
sigma: 0.25 # Pertupation standard deviation for positions
num_sample_inout: 400


# network
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

# PLOTTING PARAMETERS
freq_plot: 10 
freq_save: 50
freq_save_ply: 50
freq_val: 2 # Epochs

# PATHS
load_netN_checkpoint_path: checkpoints/demo/netN_latest