# Overfits with ground truth data

name: synthetic_first_trial_overfitting_coarse
log_path: logs/synthetic_first_trial_overfitting_coarse
gpu_ids: 0
num_threads: 4
batch_size: 1
infer: False

coarse_part: True

# data
num_views: 4
flip_x: False

# network
mlp_dim: [323, 1024, 512, 256, 128, 1]
fine_mlp_dim: [355, 512, 256, 128, 1]

train_dataroot: data/Synthetic/first_trial
val_dataroot: data/Synthetic/first_trial

# smpl
# necessary because ground truth is smplx
smpl_faces: lib/data/smpl_open3d.obj
smpl_path: Obj_Pred
obj_path: Obj 

load_netN_checkpoint_path: checkpoints/demo/netN_latest

serial_batches: True

# marching cube
resolution: 256
mc_threshold: 0.6

# debug_data: True
overfitting: True